fix: vertically paddings of buttons in settings
ShabadOS/desktop pull request #588
Opened 2020-07-08 17:10 UTC by saihaj

### Summary of PR
Increases margin top and bottom

### Tests for unexpected behavior
**Before**
![image](https://user-images.githubusercontent.com/44710980/86949237-f78d6680-c113-11ea-8f4e-790c9e305918.png)

**After**
![image](https://user-images.githubusercontent.com/44710980/86948695-222aef80-c113-11ea-97f9-7f678fd19b2b.png)

### Time spent on PR
5 mins

### Linked issues
Fix #519 

### Reviewers
@bhajneet @Harjot1Singh

2020-07-11 18:15 UTC, Harjot1Singh commented
@bhajneet does this look ok to you?

2020-07-22 14:37 UTC, bhajneet commented
@saihaj can you please share an image of the first two buttons being used vertically with this vertical-padding-fix?

2020-07-22 14:38 UTC, bhajneet commented
Also why is there no single class for buttons of this type in settings? It should not require setting padding in two css selectors.

2020-07-22 14:44 UTC, saihaj commented
> @saihaj can you please share an image of the first two buttons being used vertically with this vertical-padding-fix?

#586 will do that

2020-08-19 21:56 UTC, Harjot1Singh requested changes

2020-08-19 21:56 UTC, Harjot1Singh commented on app/frontend/src/Settings/OverlaySettings.css
> +  margin: 18px;
Why did you take off the 0 horizontal padding?

2020-08-20 15:45 UTC, Harjot1Singh approved these changes

2020-08-20 15:45 UTC, merged